# backend/docker-compose.yml
version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: eldercare
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass