services:
  # ================================
  # Backend Service
  # ================================
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: eldercare-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-change-in-production}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - DATABASE_URL=file:./prisma/dev.db
    volumes:
      # Mount source code for hot reload (dev only)
      - ./server/src:/app/src
      - ./server/prisma:/app/prisma
      # Persist SQLite database
      - ./server/prisma/dev.db:/app/prisma/dev.db
      # Persist reports
      - ./server/reports:/app/reports
      # Persist FHIR samples
      - ./server/data:/app/data
    networks:
      - eldercare-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  # ================================
  # Frontend Service
  # ================================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eldercare-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - eldercare-network
    restart: unless-stopped

networks:
  eldercare-network:
    driver: bridge

volumes:
  # Named volumes for persistent data
  db-data:
  reports-data:

