app = "eldercare-assist-ai-mvp"
primary_region = "syd"  # Sydney region; adjust as needed

[build]
  dockerfile = "backend/Dockerfile"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1